export const stocks = [
  {
    symbol: "AAPL",
    name: "Apple, Inc.",
    price: 254.24,
    change: -4.03,
    changePercent: -1.56,
    logo: "https://logo.clearbit.com/apple.com",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    price: 227.56,
    change: 2.49,
    changePercent: 1.11,
    logo: "https://logo.clearbit.com/amazon.com",
  },
  {
    symbol: "ARGT",
    name: "Global X MSCI Arg...",
    price: 74.23,
    change: 4.5,
    changePercent: 6.47,
    logo: "/placeholder.svg",
  },
  {
    symbol: "DIS",
    name: "The Walt Disney C...",
    price: 111.0,
    change: -0.84,
    changePercent: -0.75,
    logo: "https://logo.clearbit.com/disney.com",
  },
  {
    symbol: "ET",
    name: "Energy Transfer E...",
    price: 16.64,
    change: -0.02,
    changePercent: -0.11,
    logo: "/placeholder.svg",
  },
  {
    symbol: "GBTC",
    name: "Grayscale Bitcoin ...",
    price: 95.01,
    change: -1.88,
    changePercent: -1.94,
    logo: "/placeholder.svg",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc. - Cla...",
    price: 241.25,
    change: -3.06,
    changePercent: -1.25,
    logo: "https://logo.clearbit.com/google.com",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporat...",
    price: 522.79,
    change: -2.42,
    changePercent: -0.46,
    logo: "https://logo.clearbit.com/microsoft.com",
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    price: 342.88,
    change: 8.45,
    changePercent: 2.53,
    logo: "https://logo.clearbit.com/tesla.com",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 891.23,
    change: 15.67,
    changePercent: 1.79,
    logo: "https://logo.clearbit.com/nvidia.com",
  },
  {
    symbol: "META",
    name: "Meta Platforms, Inc.",
    price: 478.32,
    change: -5.21,
    changePercent: -1.08,
    logo: "https://logo.clearbit.com/meta.com",
  },
  {
    symbol: "NFLX",
    name: "Netflix, Inc.",
    price: 612.45,
    change: 12.34,
    changePercent: 2.06,
    logo: "https://logo.clearbit.com/netflix.com",
  },
];
